import type { Metadata } from "next";
import { Inter  } from "next/font/google";
import "./globals.css";
import ReduxProvider from "@/redux/ReduxProvider";
import Navbar from "@/components/Navbar";
import { NextIntlClientProvider } from "next-intl";
import {getMessages} from 'next-intl/server';
import Footer from "@/components/Footer";

const inter = Inter({
  weight: ['400','600', '700'],
  subsets: ["latin"],
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const messages = await getMessages();
  return (
    <html lang="en">
      <body
        className={`antialiased dark:bg-colorBgDark bg-colorBgLight ${inter.className}`}
      >
        <NextIntlClientProvider messages={messages}>
        <ReduxProvider>
          <Navbar />
          {children}
          <Footer/>
        </ReduxProvider>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
